### ISSUE TITLE
a way to make stream-bytes produce multiple http chunks

### ISSUE THREAD

**Issue by apmckinlay** [kennethreitz/httpbin#204]
Currently (unless I'm missing something) the chunk_size parameter on stream-bytes controls the block size used to write the data to the socket. But the entire data is still sent as one HTTP chunk i.e. there is only one total size followed by the data.

Would it be reasonable to have chunk_size control the size of the HTTP chunks? Or if not, maybe another parameter to control that?

I don't know Python so I'm not sure how feasible that is.

Thanks for a great tool.

**Comment by andreasf** [comment]
The chunk_size parameter on stream-bytes actually works as it should. The problem with _httpbin.org_ is that they use nginx as a reverse proxy, and apparently it merges all chunks into a single one. I'd suggest turning off `proxy_buffering` in nginx or exposing gunicorn directly.

**Comment by sigmavirus24** [comment]
@andreasf considering httpbin is hosted on heroku (last I checked) I doubt that's plausible.

**Comment by johnsheehan** [comment]
It is not hosted on Heroku, but I will look into making this change with the team. It has a low probability of happening quickly though.

**Comment by apmckinlay** [comment]
Thanks everyone!
