### ISSUE TITLE
Making a request using an UTF-8 param fails with curl

### ISSUE THREAD

**Issue by thefosk** [kennethreitz/httpbin#210]
I'm trying to execute the following `GET` request with curl:

``` bash
curl "http://httpbin.org/get?nick=しまりん"
```

but it fails with:

``` html
<html><body><h1>400 Bad request</h1>
Your browser sent an invalid request.
</body></html>
```

**Comment by sigmavirus24** [comment]
This is something that used to work on Heroku. I wonder if this is a result of the transition to @runscope's infrastructure.

**Comment by sigmavirus24** [comment]
If I run httpbin locally, this works just fine. The app itself doesn't have an issue.
