### ISSUE TITLE
Add Client PKI

### ISSUE THREAD

**Issue by hborders** [kennethreitz/httpbin#221]
1. Create a public/private key pair and share them both on httpbin.
2. Add an [optional TLS rule](http://ryandlane.com/blog/2010/07/29/requiring-ssl-client-authentication-in-a-user-friendly-way-in-apache/) so that the client's private key is accepted if provided
3. Create an endpoint that notices whether the connection is authenticated or not and notifies the user.

**Comment by johnsheehan** [comment]
This is an interesting idea. The TLS stuff I think is separate from HTTP concerns though (see https://github.com/Runscope/httpbin/issues/213 for more).

Can you tell us more about the cases you're looking to test? It always helps to hear the underlying problems that led you to this proposed solution.

**Comment by hborders** [comment]
I agree that TLS is technically separate from HTTP concerns, but the two are used together so often that I thought you might want to integrate them.

Maybe you guys could make tlsbin? :)

I'm making an iOS app, and iOS' HTTP client mixes HTTP and TLS auth together into a single API, so it's easiest for me to test them against the same server.
