### ISSUE TITLE
/image doesn't appear to work

### ISSUE THREAD

**Issue by kennethreitz** [kennethreitz/httpbin#225]

**Comment by eerne** [comment]
I too got a 500, when requesting the path with npm request.

The solution is to request the url with an Accept header containing image/webp 
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Then httpbin returned an image

```json
		"pathname": "/image",
		"type": "image/webp",
		"statusCode": 200,
		"statusMessage": "OK",
		"headers": {
			"content-type": "image/webp",
			"content-length": 10568
		}
```

**Comment by eerne** [comment]
I am not sure whether this is right or wrong, but:
returns nothing ```curl http://httpbin.org/image``` 
get something ```curl --header "Accept:text/html,image/webp,*/*;q=0.8" http://httpbin.org/image```

**Comment by darrelmiller** [comment]
The problem was related to attempting to access the accept header when there was no accept header.  I chose to return a default media type (image/png) if no accept header was provided.  Is there any reason anyone feels we should return 406 instead?

**Comment by eerne** [comment]
How about 300 Multiple Choices ? I am not sure how "serve several equivalent contents for a given URI" really works (source https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation)

**Comment by darrelmiller** [comment]
@eerne We could do that, but there are no standard media types for returning the available choices and I'm pretty sure no-one wants to start parsing link headers.  It would be nice to stick to the principle of least surprise.  If someone asks httpbin for an image, I'm assuming they want an image back, regardless of whether they bothered to set the accept header or not.  If you care about the format, then either set the accept header or use one of the variant specific resources.
