### ISSUE TITLE
Support status code and delay on a single URL

### ISSUE THREAD

**Issue by ofri65** [kennethreitz/httpbin#229]
Hi Guys,

It would be great if you could add a single URL that will support both status code (as you do with /status/:code) and delay (as you do in /delay/:n).
This is very useful.

Thanks
Ofri

**Comment by kcharwood** [comment]
Was coming here to request the same feature. This would be great!

**Comment by sigmavirus24** [comment]
I'm not sure about @johnsheehan's opinion on this (or @kevin1024's) but I'm not convinced this is something we'd like to support. Could either of you provide context as to why you are requesting this? What are you trying to test?

**Comment by kcharwood** [comment]
I'd like to be able to test some error states with delay. I've seen a few race condition failures in my testing setup where the 404 returns before my wait code is ready in XCTest, causing my expectation to never fire.

If I could do /delay/5/status/404, that would solve my problem!

**Comment by johnsheehan** [comment]
There was some offline discussion about a 'composable' endpoint where you could do something like `httpbin.org?status=404&delay=10` which I think would be more broadly useful. I'm personally not in favor of making the single-purpose endpoints multi-purpose.

**Comment by kcharwood** [comment]
I do like that idea! :+1:

**Comment by sigmavirus24** [comment]
Yeah I can get behind a single endpoint that's sort of composable. It'll need some refactoring of the code base but I'm up for that.

**Comment by j-manu** [comment]
Is the composible endpoint still in the roadmap?
