### ISSUE TITLE
Allow auth endpoints to accept username and password via POST / query string params

### ISSUE THREAD

**Issue by benvinegar** [kennethreitz/httpbin#232]
The URL scheme for these endpoints (e.g. `/basic-auth/:user/:passwd`) cannot be constructed using a standard HTML `<form>` ... unless you hardcode the values into the URL, or use JavaScript to amend the URL before submission.

**Comment by darrelmiller** [comment]
I'm assuming you would rather have /basic-auth?user=xxx&password=yyy  ?

**Comment by sigmavirus24** [comment]
Could you provide an example of why you're using httpbin as part of a form?

**Comment by benvinegar** [comment]
I use jsbin + httpbin to demonstrate a variety of different web application patterns without having to implement/host them myself. Some using plain HTML, some using JavaScript + XMLHttpRequest, JSONP, etc.

**Comment by benvinegar** [comment]
Also, I'd be glad to submit a PR if you feel this feature request is an acceptable change.

**Comment by sigmavirus24** [comment]
I'm torn. On the one hand I really really dislike having multiple ways to do it. On the other, I wouldn't necessarily be against just scrapping the way the endpoint currently works and moving towards only using args (although that would break things for a lot of people)

**Comment by darrelmiller** [comment]
@sigmavirus24 We could redirect to the new query parameter format to limit the damage to existing applications.  That would also provide incentive for people to move to the new format to avoid the extra round trip.

**Comment by kevin1024** [comment]
How about if we were to version httpbin?  /v2/ endpoints could behave differently.

Would increase the code complexity a lot though.

**Comment by johnsheehan** [comment]
Would prefer not to have another version.

**Comment by sigmavirus24** [comment]
If we were to version endpoints, using `/v2` would cause me to tear my hair out. There's ways of versioning using the `Accept` header that work super well and reduce complexity (even though versioning endpoints significantly increases complexity no matter how you do it).

I like @darrelmiller's compromise but I think the mindset that "this is used for [requests](/kennethreitz/requests) to test against" is something that biases me. I know for one that lots of HTTP clients don't automatically follow redirects so this would still break things for them.

What if we restructure our endpoints and provide a deprecation period? We really have no easy way to signal this to people though. We're not a real API so no one's really subscribed to anything we could use to warn them.
