### ISSUE TITLE
Support /relative-redirect-to 

### ISSUE THREAD

**Issue by eerne** [kennethreitz/httpbin#234]
I would like to test agains an infinite redirect loop.
Currently this can not be tested with /redirect-to?url=/redirect-to
A relative /relative-redirect-to route would allow to setup an infinite redirect
/relative-redirect-to/relative-redirect-to

**Comment by darrelmiller** [comment]
Can you not simulate an infinite redirect with a /redirect/:n with a high value of n.  As long as n is higher than your client's max redirects then isn't that equivalent to infinite?

**Comment by eerne** [comment]
In my case it checks if the referrer is == the redirect location. Else the script is supposed to follow the redirect. It successfully redirects and follows http://httpbin.org/redirect/100 ending up at http://httpbin.org/get

So I would love to have a way of testing referrer == redirect location

But my proposal would not work "/relative-redirect-to/relative-redirect-to".

**Comment by sigmavirus24** [comment]
I understand and can sympathize with the request here, I'm just not certain HTTPbin needs to provide endpoints for every situation that can go wrong. I mean, if we did, we'd probably be bordering on the thousands of endpoints. I feel like [pathod](https://warehouse.python.org/project/pathod/) is what you're looking for.
