### ISSUE TITLE
readme /range

### ISSUE THREAD

**Issue by eerne** [kennethreitz/httpbin#235]
The readme states that there is a /range route.. this is gone?

/range/:n   Streams n bytes, and allows specifying a Range header to select a subset of the data. Accepts a chunk_size and request duration parameter.

**Comment by darrelmiller** [comment]
The Range function is new and hasn't been deployed into prod yet.  I'm currently testing new features and will try get these changes pushed out soon.

**Comment by eerne** [comment]
nice
