### ISSUE TITLE
/image returns 404 if accept header does not include valid media type

### ISSUE THREAD

**Issue by darrelmiller** [kennethreitz/httpbin#236]
This should either return 406 - Not Acceptable or return a default media type.

**Comment by sigmavirus24** [comment]
Could also return 400 - Bad Request

**Comment by darrelmiller** [comment]
@sigmavirus24  My poor choice of words.  I should have said "does not include a supported media type".  I'm not suggesting the media type supplied is badly formatted.  Anyway, this is not a big issue.  Probably not worth changing the behavior without some specific reason to.

**Comment by sigmavirus24** [comment]
Woops, I should have grokked that the first time around. I'm actually very much in favor of making httpbin do the right thing and follow mostly best practices (where they make sense for the project). I'm :+1: on a 406 being returned here personally.

**Comment by phouse512** [comment]
Is anyone working on this? I can take a stab at this if nobody is.

**Comment by phouse512** [comment]
See PR #250 @darrelmiller @sigmavirus24
