### ISSUE TITLE
Drip not dripping?

### ISSUE THREAD

**Issue by jeroen** [kennethreitz/httpbin#252]
Is the drip api still working? I tried this [jsfiddle](http://jsfiddle.net/wtdfg17q/) and also curl but it seems like the data gets delayed until the end. Perhaps your CDN is waiting for the request to complete or so?

```
curl https://httpbin.org/drip?duration=5&numbytes=5000
```

**Comment by sigmavirus24** [comment]
It could be Heroku's proxy that is doing this. I am confident the endpoint is written correctly because I've stolen the basic ideas for other flask projects I've written.

**Comment by jeroenooms** [comment]
Could be. I am seeing `Server:nginx`, is that Heroku? I'd be interested to know how nginx needs to be configured to support dripping/streaming.

**Comment by sigmavirus24** [comment]
Er, put it like this. Last I checked, @Runscope/httpbin 's engineers who manage the deployment were still using Heroku. If you run httpbin locally, do you still see the same issue? My guess is no. (I don't have time to check right now.)

**Comment by jeroenooms** [comment]
Actually yes I do see the same problem locally.

**Comment by sigmavirus24** [comment]
That's bizarre. According to [Flask's documentation](http://flask.pocoo.org/docs/0.10/patterns/streaming/#basic-usage), [our endpoint](https://github.com/Runscope/httpbin/blob/master/httpbin/core.py#L470) should work correctly.

I wonder if Flask/werkzeug behave differently if there's a `Content-Length` header. Can you modify your local copy to get rid of that?

**Comment by jeroenooms** [comment]
That doesn't seem to fix it.

**Comment by sigmavirus24** [comment]
Interesting

**Comment by brandon-shannon** [comment]
Same issue.  I see 8s for TTFB when I send a delay of 0 and a duration of 8.

**Comment by cup** [comment]
https://github.com/postmanlabs/httpbin/issues/252
https://github.com/postmanlabs/httpbin/issues/348
https://github.com/postmanlabs/httpbin/issues/417
https://github.com/postmanlabs/httpbin/issues/541
