### ISSUE TITLE
non free file forms-post.html

### ISSUE THREAD

**Issue by danstender** [kennethreitz/httpbin#260]
We've came across this working on the Debian package of httpbin (which is coming up, soon): /httpbin/templates/forms-post.html is under the W3C Document License which isn't FOSS free ("no right to create modifications or derivatives") and therefore we had to strip it off from the upstream tarball we use. Maybe you would like to exchange that with something else?

**Comment by danstender** [comment]
BTW, towards httpbin/license/UTF-8-demo.txt no licensing statement at all could be found, so we've had to extract that either (nitpicky, I know, but this is how it works ...). I've contacted Markus Kuhn if he would like to add a license statement.

**Comment by johnsheehan** [comment]
I'm not even sure why `/forms/post` is there but yes, I'm open to a replacement.

**Comment by sigmavirus24** [comment]
@johnsheehan probably because someone wanted to test something like using BeautifulSoup + an HTTP Agent and someone said "sure why not".

**Comment by danstender** [comment]
We've got Httpbin already in Debian now: https://tracker.debian.org/pkg/httpbin (very new, package tracker page not yet populated)
