### ISSUE TITLE
Deployment issue? Using 23.22.14.18 is working but not 54.175.219.8

### ISSUE THREAD

**Issue by Diastro** [kennethreitz/httpbin#321]
Hi,

We've been using the httpbin service for a while and we have been seeing some issue lately. For some reason httpbin.org sometimes resolves to 54.175.219.8 and when it does we keep getting "Connected reset by peer". However, when the adress resolves to 23.22.14.18 everything is working fine.

Is there any difference between the 2 deployments?

Thanks,

**Comment by sigmavirus24** [comment]
@johnsheehan I'm not sure who to ping at Runscope for this.
