### ISSUE TITLE
Random sub-domains no longer open the website

### ISSUE THREAD

**Issue by macroshadow** [kennethreitz/httpbin#334]
Up until yesterday, any random sub-domain would open the website, i.e. https://dsaf.httpbin.org/ would open the same page as https://httpbin.org/ (not redirected), just like https://eu.httpbin.org/ still does now.
Since yesterday, it gives a "This site can’t be reached" error (DNS_PROBE_FINISHED_NXDOMAIN) for a random sub-domain.

**Comment by sigmavirus24** [comment]
Looks as though the certificate was generated yesterday. Ostensibly the old deployment had a wild-card certificate and a way of having all DNS resolve to httpbin.org. It looks as though httpbin's deployment may have been moved from Runscope back to Heroku. Without more insight into how it's deployed, there's little to be done.

I'm not sure this behaviour was ever documented as supported.

**Comment by kennethreitz** [comment]
This is unsupported behavior, unfortunately.
