### ISSUE TITLE
Create DC/OS package for httpbin

### ISSUE THREAD

**Issue by msabramo** [kennethreitz/httpbin#335]
This would be another option for easily deploying httpbin - to a Mesosphere DC/OS cluster, by simply doing `dcos package install httpbin`. 

I've already submitted a PR for this - https://github.com/mesosphere/universe/pull/1003, though it's not merged yet. 

I thought folks who follow this repo might be interested to know.

**Comment by kennethreitz** [comment]
thanks for letting us know!

**Comment by kennethreitz** [comment]
once it's deployed, we can add it to the official deployments list
