### ISSUE TITLE
SSL connect error (negative port redirect)

### ISSUE THREAD

**Issue by jeroen** [kennethreitz/httpbin#336]
Since a few days the https server is doing strange redirects invalid SSL responses when setting a wrong hostname. It seems to redirect to a negative port number?

```sh
ping httpbin.org
# PING httpbin.org (54.243.85.55): 56 data bytes

curl https://54.243.85.55
# curl: (35) Unknown SSL protocol error in connection to 54.243.85.55:-9838
```

This has broken my unit test. I understand that the SSL cert will not work without a valid hostname, but it should still work with `--insecure` or `curlopt_ssl_verifyhost=0`. Currently we just get SSL handshake errors, which is bad.

**Comment by kennethreitz** [comment]
a hostname is required with this implementation of SSL termination.
