### ISSUE TITLE
How to add a delay to a post request

### ISSUE THREAD

**Issue by geekarist** [kennethreitz/httpbin#338]
Hello,

I can see how to delay the response for a GET request:

    http://httpbin.org/delay/10

I can see how to make a POST request:

    curl -X POST http://httpbin.org/post

But how could I make a POST request and add a delay? I tried this:

```
curl -X POST http://httpbin.org/post/delay/10

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
```

Thanks for any help,
Christophe.

**Comment by kennethreitz** [comment]
not at this time.

**Comment by sudsy** [comment]
Looking through the other issues and the source code it seems like this is supported. I'm a bit confused about what needs to be done to support this. It is very useful to be able to test what happens when a webservice takes too long to respond even when posting data to it.

**Comment by G-Raghukiranreddy** [comment]
hi geekartist, you can do it like this curl -X POST http://httpbin.org/post/?delay=${delaytime}
