### ISSUE TITLE
Feature: Report arbitrary paths

### ISSUE THREAD

**Issue by jaraco** [kennethreitz/httpbin#339]
I'd like to use httpbin to demonstrate an issue with the way a browser handles certain inputs in the URL bar. I want to use httpbin to reflect the path of the request. I'm imagining something like:

https://httpbin.org/path_info/foo/bar?x=3

Would return an HTML and/or JSON result indicating that the path was `/path_info/foo/bar` and the query string was `{"x": "3"}`. I would like it to report the unquoted version of the path, but it might also be nice for it to report the quoted version.

I see now that `/get` already handles the qs aspect, so perhaps it would be sufficient for `/get` to be extended to allow arbitrary paths after `/get/` and to include the path info in the response (leaving `/get` to behave as it does now, as a degenerate form of the path-handling behavior).

Would this behavior be a suitable enhancement for httpbin?

**Comment by sigmavirus24** [comment]
There are other services that already do this, e.g., [requestbin](https://requestb.in/). This isn't self-hosted/pip-installable, but it exists and we've stated in the past that we don't want to replicate it here.

**Comment by sigmavirus24** [comment]
I'll let Kenneth way in, but I'm +1 on closing this.

**Comment by jaraco** [comment]
I don't think requestbin supports arbitrary paths. I just created a bin, but I get a 404 if I try to access a subpath of that bin.

```
$ curl -X POST -d "fizz=buzz" http://requestb.in/vndjy1vn/foo
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
```

**Comment by jaraco** [comment]
Perhaps I should explain why I came to want this feature. I was constructing a JSON query in a URL for [mongs](/whit537/mongs) and I wanted to verify what it was that the browser was requesting (what transformations were being made on a URL path like `/query/{$not: {$regex: "substring"}}/`).

**Comment by jaraco** [comment]
You're probably right that nobody is going to need this, especially since [emerging standards are rendering URL paths unusable anyway](https://bugzilla.mozilla.org/show_bug.cgi?id=1348876), and one could probably use Developer Tools to get the details. So no need to fuss about it or spend any more time on it.
