### ISSUE TITLE
Regression with chunked transfer encoding?

### ISSUE THREAD

**Issue by pb-** [kennethreitz/httpbin#340]
I'm using https://httpbin.org and it looks like chunked transfer encoding does not work any more as expected:

```
$ curl -X POST https://httpbin.org/post \
 -d '{"message":"BLA"}' \
 -H 'Content-Type: application/json' \
 -H 'Transfer-Encoding: chunked'
{
  "args": {}, 
  "data": "", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "*/*", 
    "Connect-Time": "1", 
    "Connection": "close", 
    "Content-Type": "application/json", 
    "Host": "httpbin.org", 
    "Total-Route-Time": "0", 
    "Transfer-Encoding": "chunked", 
    "User-Agent": "curl/7.50.1", 
    "Via": "1.1 vegur", 
    "X-Request-Id": "2a06bd5b-06dc-4ced-ac89-fe83cbb6771c"
  }, 
  "json": null, 
  "origin": "<removed>", 
  "url": "https://httpbin.org/post"
}
```

Observe that `data` and `json` do not contain the posted data. The same request works as expected without chunked transfer encoding:

```
$ curl -X POST https://httpbin.org/post \
 -d '{"message":"BLA"}' \
 -H 'Content-Type: application/json'
{
  "args": {}, 
  "data": "{\"message\":\"BLA\"}", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "*/*", 
    "Connect-Time": "0", 
    "Connection": "close", 
    "Content-Length": "17", 
    "Content-Type": "application/json", 
    "Host": "httpbin.org", 
    "Total-Route-Time": "0", 
    "User-Agent": "curl/7.50.1", 
    "Via": "1.1 vegur", 
    "X-Request-Id": "dfbaa440-9871-4a3c-b482-35a68459722a"
  }, 
  "json": {
    "message": "BLA"
  }, 
  "origin": "<removed>", 
  "url": "https://httpbin.org/post"
}
```

Am I missing something?

**Comment by sigmavirus24** [comment]
You're not missing anything. This does look like a regression.

For @kennethreitz:

```py
>>> r = requests.post('https://httpbin.org/post', data=iter(('foo', 'bar', 'bogus')))
>>> r.request.headers['Transfer-Encoding']
>>> r.json()['data']
>>> pprint.pprint(r.json())
{u'args': {},
 u'data': u'',
 u'files': {},
 u'form': {},
 u'headers': {u'Accept': u'*/*',
              u'Accept-Encoding': u'gzip, deflate',
              u'Connect-Time': u'0',
              u'Connection': u'close',
              u'Host': u'httpbin.org',
              u'Total-Route-Time': u'0',
              u'Transfer-Encoding': u'chunked',
              u'User-Agent': u'python-requests/2.13.0',
              u'Via': u'1.1 vegur',
              u'X-Request-Id': u'0c60c510-80e2-4d97-a02a-11b006f38376'},
 u'json': None,
 u'origin': u'...',
 u'url': u'https://httpbin.org/post'}
```

**Comment by kennethreitz** [comment]
I don't remember this previously being a problem when hosting on Heroku.

**Comment by sigmavirus24** [comment]
> I don't remember this previously being a problem when hosting on Heroku.

Sadly it's reproducible.

**Comment by kennethreitz** [comment]
@sigmavirus24 you reproduced it on another app on heroku?

**Comment by kennethreitz** [comment]
I'm down with adding a "on heroku" mode to httpbin, that removes that endpoint from the html, but keeps it in the distributed version.

**Comment by sigmavirus24** [comment]
@kennethreitz I didn't try reproducing with a different app, I was just able to reproduce that httpbin seems broken. I can try spinning up a different app over the weekend to see if I can reproduce this there too

**Comment by kennethreitz** [comment]
@sigmavirus24 sounds great

**Comment by graingert** [comment]
@kennethreitz @sigmavirus24 I get a broken pipe, when running locally on raw weukzeug https://travis-ci.org/kevin1024/pytest-httpbin/jobs/218194179 https://github.com/kevin1024/pytest-httpbin/pull/38/files#diff-db42f37e1c90bb185d0251b14ddd12e0R47

**Comment by graingert** [comment]
```
Python 3.6.1 (default, Mar 22 2017, 06:17:05) 
[GCC 6.3.0 20170321] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from httpbin import app as httpbin_app
>>> from pytest_httpbin import serve, certs
>>> server = serve.Server(application=httpbin_app)
>>> server.start()
>>> server
<Server(<class 'pytest_httpbin.serve.Server'>, started 140641123542784)>
>>> server.port
35117
```
$ curl -X POST http://localhost:35117/post \
 -d '{"message":"BLA"}' \
 -H 'Content-Type: application/json'
{
  "args": {}, 
  "data": "", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "*/*", 
    "Content-Length": "", 
    "Content-Type": "application/json", 
    "Host": "localhost:35117", 
    "Transfer-Encoding": "chunked", 
    "User-Agent": "curl/7.51.0"
  }, 
  "json": null, 
  "origin": "127.0.0.1", 
  "url": "http://localhost:35117/post"
}
```

**Comment by Lukasa** [comment]
Ok, so that seems to be a werkzeug issue. Using twisted as the WSGI server (`twist web --wsgi httpbin.app`) I get this:

```json
{
  "args": {}, 
  "data": "{\"message\": \"bla\"}", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "*/*", 
    "Content-Length": "18", 
    "Content-Type": "application/json", 
    "Host": "localhost:8080", 
    "User-Agent": "curl/7.51.0"
  }, 
  "json": {
    "message": "bla"
  }, 
  "origin": "127.0.0.1", 
  "url": "http://localhost:8080/post"
}
```

So my guess would be that this is an interaction between the werkzeug server and httpbin.

**Comment by Lukasa** [comment]
However, the chunked problem is alive and well. Again, testing with Twisted:

```
>>> import requests
>>> from pprint import pprint as p
>>> def gen():
...     yield b"hello"
...     yield b"world"
... 
>>> r = requests.post('http://localhost:8080/post', data=gen())
>>> p(r.json())
{'args': {},
 'data': '',
 'files': {},
 'form': {},
 'headers': {'Accept': '*/*',
             'Accept-Encoding': 'gzip, deflate',
             'Connection': 'keep-alive',
             'Content-Length': '',
             'Content-Type': '',
             'Host': 'localhost:8080',
             'Transfer-Encoding': 'chunked',
             'User-Agent': 'python-requests/2.13.0'},
 'json': None,
 'origin': '127.0.0.1',
 'url': 'http://localhost:8080/post'}
```

Wireshark shows the chunked data being sent, so that issue is somewhere in the httpbin codebase.

**Comment by Lukasa** [comment]
So I just double-checked, and twisted has definitely received the chunked data and de-chunked it before passing it to Flask. So this rather suggests that Flask might be dropping the ball here: by the time it gets to httpbin the data is missing, so presumably somewhere in Flask the data is getting lost.

**Comment by graingert** [comment]
@Lukasa https://github.com/pallets/flask/issues/367 ?

**Comment by Lukasa** [comment]
No. Flask isn't seeing the chunked data here: Twisted has parsed it before Flask ever gets a chance to see it.

**Comment by graingert** [comment]
And another pytest-httpbin issue https://github.com/kevin1024/pytest-httpbin/issues/33#issuecomment-193709617

**Comment by Lukasa** [comment]
Ok, so I wrote a really simple repro of this with Flask. Run the following Flask application:

```python
from flask import Flask, request
app = Flask(__name__)

@app.route('/', methods=['GET', 'POST'])
def hello_world():
        return request.data
```

With the following test script:

```python]
import requests

def gen():
    yield b"hello"
    yield b"world"

print("Making first request")
r = requests.post('http://localhost:8000/', data=b'helloworld')
print("Got: %s" % r.content.decode('utf-8'))
print("Making second request")
r = requests.post('http://localhost:8000/', data=gen())
print("Got: %s" % r.content.decode('utf-8'))
```

Gives the output:

```
Making first request
Got: helloworld
Making second request
Got: 
```

I ran this test with gunicorn. This suggests that the flask data is going...somewhere. I don't know where yet.

**Comment by Lukasa** [comment]
Reported as pallets/flask#2229.

**Comment by kennethreitz** [comment]
✨🍰✨

**Comment by tmenier** [comment]
Why was this issue closed? Chunked encoding is still busted.

**Comment by graingert** [comment]
@tmenier this issue has never been closed

**Comment by tmenier** [comment]
doh...my bad.

**Comment by davidism** [comment]
The way to support this is to wrap your app in the following middleware when running with Gunicorn (or another server that supports chunked encoding).

```python
class InputTerminated:
    def __init__(self, wsgi_app):
        self.wsgi_app = wsgi_app

    def __call__(self, environ, start_response):
        environ['wsgi.input_terminated'] = True
        return self.wsgi_app(environ, start_response)

app.wsgi_app = InputTerminated(app.wsgi_app)
```

**Comment by skyline75489** [comment]
Curl seems to be not working well with httpbin right now:

```plaintext
$ curl -F filedata=@winpp.zip http://localhost:5000/post --header "Transfer-Encoding: chunked" --header " Expect:"
curl: (56) Recv failure: Connection was reset
```

I'm using curl 7.51.0 and httpbin 0.5.0 running with `python -m httpbin.core`.

**Comment by kennethreitz** [comment]
Can you try again? https://github.com/kennethreitz/httpbin/issues/370

**Comment by kennethreitz** [comment]
That did not seem to fix this problem.

**Comment by kevin1024** [comment]
OK, so 2e94212886e4c9531b8ba7f55f4fb0b8134e10ac broke pytest-httpbin (and caused some issues with requests as well) since pytest-httpbin uses werkzeug.

See also:

* requests/requests#4261
* requests/requests#4258
* requests/requests#4259

BUT since it didn't fix anything, I think we will remove it for the next httpbin release.

**Comment by kennethreitz** [comment]
thanks @kevin1024

**Comment by kennethreitz** [comment]
i trusted that @davidism knew what he was talking about hehehe

**Comment by davidism** [comment]
Hmm, I'll look again when I get a chance. That should have worked with Gunicorn.

**Comment by kennethreitz** [comment]
No worries @davidism :)

**Comment by 0x1eaf** [comment]
Hi)

Currently httpbin.org responds with 411 status and “Length Required” message to any POST/PUT requests that are sent using chunked encoding…

```
$  curl -F filedata=@.gitignore http://httpbin.org/post --header "Transfer-Encoding: chunked" --header "Expect:"
<html><head><title>Length Required</title></head><body><p>Length Required.</p></body></html>
```

Are there any plans to fix this?

**Comment by kennethreitz** [comment]
@0x1eaf you are complaining about a free service :)

Pull requests accepted!

**Comment by tmenier** [comment]
Ouch. Sounded like a polite inquiry to me, not complaining. Can't do that because it's free?

**Comment by kennethreitz** [comment]
Sorry for being grumpy — been a long day :)

**Comment by graingert** [comment]
Might be an idea to drop the endpoint (at least from the docs) while the
kinks are being worked out?

**Comment by tmenier** [comment]
I'd contribute a fix myself if not for the little hurdle of learning Python. But either way, thanks for providing this service, it's been invaluable :)

**Comment by javabrett** [comment]
The current upsteam issue for this is https://github.com/pallets/werkzeug/issues/1149 .  Note that if `environ['wsgi.input_terminated']` can be set, the chunked input stream won't be blanked.

**Comment by javabrett** [comment]
I have a general question about writing a test to demonstrate this bug and any candidate fix.

Am I right in understanding that the tests in https://github.com/kennethreitz/httpbin/blob/master/test_httpbin.py are purely unit tests, test via the Flask app interface, and requests don't actually pass through a real server socket?

I wondering if some sort of system test will be required for this.  I'm assuming current tests have nothing to do with gunicorn behaviour for example.  It is likely that the behaviour here will vary between what is seen in the unit tests compared to a live Flask and also a live Gunicorn server.

Should some sys tests be added, and any guidance on frameworks for that?

**Comment by javabrett** [comment]
Here’s -my- understanding of this issue.

* There is a proposal to add `environ` `wsgi.input_terminated`, but it is not widely adopted.  Unicorn does not set this, although it does seem to provide input termination.  The result is that the data input stream is emptied.  See:
  * https://gist.github.com/mitsuhiko/5721107
  * https://gist.github.com/mitsuhiko/5721547
  * Werkzeug added support in https://github.com/pallets/werkzeug/commit/918cc8614eb76147432995042522f853b536f770 
  * This issue is relevant: https://github.com/pallets/werkzeug/issues/1149
* There’s a commit https://github.com/dawran6/werkzeug/commit/032c2c78b274f7cd4b204c40d46678eeea74f719 on Werkzeug master, unreleased as at 0.12.2, which adds a `max_content_length` environ. Might be some value in using that when it is released, but I don’t think it’s compelling enough to patch.
* If you set  `environ` `wsgi.input_terminated` for a chunked request to `gunicorn`, the data stream is not nulled and it works.  If you do the same for flask, it will hang.

**Comment by davidism** [comment]
* uWSGI and mod_wsgi both support `wsgi.input_terminated` now, and I'm fairly sure Gunicorn supports it or at least is open to it.
* The `max_content_length` patch was reverted, it was based on some incorrect assumptions on my part.
* Ironically, support for `input_terminated` in Werkzeug's dev server is only now being added in pallets/werkzeug#1198.

I'm curious why the middleware I suggested above (https://github.com/kennethreitz/httpbin/issues/340#issuecomment-317052446) didn't work.

**Comment by tmenier** [comment]
Can I ask why this issue was closed? From my tests it doesn't appear to be fixed. Just me? Or hasn't the fix been deployed yet?

**Comment by davidism** [comment]
@tmenier the fix is not part of a released version yet.

**Comment by javabrett** [comment]
@tmenier if you build the project's `Dockerfile` you should be able to:
```
docker build --tag httpbin .
docker run -d --name httpbin -p 8080:8080 httpbin
curl -X POST http://localhost:8080/post  -d '{"message":"BLA"}'  -H 'Content-Type: application/json'  -H 'Transfer-Encoding: chunked'
{
  "args": {}, 
  "data": "{\"message\":\"BLA\"}", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "*/*", 
    "Content-Type": "application/json", 
    "Host": "localhost:8080", 
    "Transfer-Encoding": "chunked", 
    "User-Agent": "curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.21 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2"
  }, 
  "json": {
    "message": "BLA"
  }, 
  "origin": "172.17.0.1", 
  "url": "http://localhost:8080/post"
}
```

A couple of follow-up wquestions of my own:

* Should https://httpbin.org or some sub-page return the exact version-number of the project, either in the response or as a header?  Might help with this sort of enquiry.
* Above I wrote:

> I have a general question about writing a test to demonstrate this bug and any candidate fix.

... asking whether there were any current project integration-style tests that run via the Gunicorn server, versus just running in Flask.  If there aren't, is it worthwhile adding something?  That would help with tests that require Gunicorn to assert a fix.

**Comment by kennethreitz** [comment]
deployed latest to production

**Comment by davidism** [comment]
@kennethreitz I think this exact fix is in Werkzeug now, so you could technically remove this patch if you're using the latest version of Werkzeug.

**Comment by javabrett** [comment]
@davidism nice we should try that.

Should we spin-up a framework to run some integration tests? I'm still a little uneasy that all existing tests might only run through the internals of Flask.

**Comment by davidism** [comment]
I may have been misremembering, it's been a while. I think Werkzeug's dev server now sets `wsgi.input_terminated` correctly, and I reached out to other WSGI servers but not all of them set the flag yet.

**Comment by javabrett** [comment]
https://github.com/pallets/werkzeug/commit/8eb665a94aea9d9b56371663075818ca2546e152 since Werkzeug 0.13.

httpbin is now `werkzeug = ">=0.14.1"`, but was not as was locked to `0.12.1` at the time the patch was merged, so yes probably time to re-test without it.

**Comment by javabrett** [comment]
I reverted my patch commits and tested (manually, there is no automated test available for this) in a Docker (so running Gunicorn) and httpbin did not return the sent-data - it returned `"json": null`.  So something is still not right.

**Comment by javabrett** [comment]
@samoconnor yes I see the same, and also note that httpbin.org is not hosted using Gunicorn, at least not directly.  I don't have the technical details of that deployment.  The fix as it stands only works for Gunicorn-hosted httpbin.

Response-header from localhost Docker-hosted:
```
HTTP/1.1 200 OK
Server: gunicorn/19.7.1
...
X-Powered-By: Flask
```
Response-header from httpbin.org:
```
HTTP/1.1 411 Length Required
Server: meinheld/0.6.1
Via: 1.1 vegur
```
So clearly the hosting is different, and likely there is some reverse-proxying.  Might have to wait for a response from someone familiar with the hosting set-up.

In the interim I can assure you the Docker version works ...

**Comment by javabrett** [comment]
I can further confirm that if the currently-published Docker is run with non-standard launch, instead running the following (borrowing from https://github.com/kennethreitz/httpbin/blob/master/Procfile#L1 )

    gunicorn httpbin:app -b 0.0.0.0:8080 --log-file - --worker-class="egg:meinheld#gunicorn_worker"

... also yields:

```
curl -v -X POST http://localhost:8080/post -d '{"message":"BLA"}'  -H 'Content-Type: application/json'  -H 'Transfer-Encoding: chunked' 
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> POST /post HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type: application/json
> Transfer-Encoding: chunked
> 
> 11
* upload completely sent off: 24 out of 17 bytes
* HTTP 1.0, assume close after body
< HTTP/1.0 411 Length Required
< Content-Type: text/html
< Server: meinheld/0.6.1
< 
* Closing connection 0
<html><head><title>Length Required</title></head><body><p>Length Required.</p></body></html>
```

This problem seems to occur well before Gunicorn or the middleware itself is processing the request - problem in the Meinheld Gunicorn worker?

**Comment by samoconnor** [comment]
should this issue be re-opened?

**Comment by javabrett** [comment]
I can reproduce the 411 coming from meinheld for a chunked-request, but don't know how to fix that yet.

**Comment by kennethreitz** [comment]
We don't have to use meinheld.

**Comment by kennethreitz** [comment]
Is the problem reproduced when meinheld is dropped?

**Comment by javabrett** [comment]
This problem cannot be reproduced (e.g. in a Docker container build running Gunicorn) without the `--worker-class="egg:meinheld#gunicorn_worker"`.  This is in meinheld and I found its logic where it return 411 and wrote a failing test.  Will raise an issue and reference this issue.

**Comment by javabrett** [comment]
My code-change to meinheld was merged, so when it is next-released it will no-longer generate the 411 error-response when `Transfer-Encoding: chunked` and missing or zero `Content-Length`, which is as it should be.  I don't think there's nightly builds other than on Travis.

**Comment by kennethreitz** [comment]
How long do you think that will be? We can drop meinheld in the meantime, if needed. It's not necessary. Just helps handle bursts of traffic.

**Comment by javabrett** [comment]
There are no recent meinheld releases, but that could be needs driven, as there aren't a lot of unreleased commits: https://github.com/mopemope/meinheld/compare/v0.6.1...master .  I guess we could request a release.

If httpbin.org is very busy, perhaps it could retain meinheld and the chunked-request problem until the release, but other less-busy servers could have meinheld disabled for now.  I don't know if that's a good idea or not.  I guess it depends on whether stability or perf issues are expected on certain servers without meinheld.
