### ISSUE TITLE
newest release is 0.5.0, but "http://httpbin.org/"'s content stop in 0.2.0

### ISSUE THREAD

**Issue by baby5** [kennethreitz/httpbin#341]

**Comment by The-Compiler** [comment]
With "content", do you mean "changelog"?

**Comment by baby5** [comment]
i guess it doesn't update after 0.2.0, so 'changelog' is not newest, maybe other ''content'' is old too.

**Comment by kennethreitz** [comment]
got rid of changelog, since it was out of date.
