### ISSUE TITLE
New X-Request-Id header showing up in /get endpoint

### ISSUE THREAD

**Issue by dteirney** [kennethreitz/httpbin#342]
Hello, we've been using httpbin.org to check that some of our proxy configuration is sending through the headers that we expect (and not ones that we don't expect).

Previously, we were ensuring that we had properly "turned off" generation of an X-Request-Id header in our software which was working great. However, httpbin is now always returning an X-Request-Id header so these tests are now failing.

Additionally, if an X-Request-Id header is sent to httpbin, it is being overriden in the response by the X-Request-Id that httpbin seems to be generating.

Is the "headers" array for the /get resource only supposed to contain the headers that were received by httpbin?

```
$ curl -v http://httpbin.org/get
*   Trying 50.19.93.247...
* TCP_NODELAY set
* Connected to httpbin.org (50.19.93.247) port 80 (#0)
> GET /get HTTP/1.1
> Host: httpbin.org
> User-Agent: curl/7.53.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Connection: keep-alive
< Server: gunicorn/19.7.0
< Date: Tue, 21 Mar 2017 22:40:34 GMT
< Content-Type: application/json
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
< Content-Length: 356
< Via: 1.1 vegur
<
{
  "args": {},
  "headers": {
    "Accept": "*/*",
    "Connect-Time": "0",
    "Connection": "close",
    "Host": "httpbin.org",
    "Total-Route-Time": "0",
    "User-Agent": "curl/7.53.1",
    "Via": "1.1 vegur",
    "X-Request-Id": "8ebbb83a-a224-49f9-aa73-8563d1da89b7"
  },
  "origin": "202.37.75.230",
  "url": "http://httpbin.org/get"
}

$ curl -v -H "X-Request-Id: bob" http://httpbin.org/get
*   Trying 23.23.128.123...
* TCP_NODELAY set
* Connected to httpbin.org (23.23.128.123) port 80 (#0)
> GET /get HTTP/1.1
> Host: httpbin.org
> User-Agent: curl/7.53.1
> Accept: */*
> X-Request-Id: bob
>
< HTTP/1.1 200 OK
< Connection: keep-alive
< Server: gunicorn/19.7.0
< Date: Tue, 21 Mar 2017 22:38:39 GMT
< Content-Type: application/json
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
< Content-Length: 356
< Via: 1.1 vegur
<
{
  "args": {},
  "headers": {
    "Accept": "*/*",
    "Connect-Time": "1",
    "Connection": "close",
    "Host": "httpbin.org",
    "Total-Route-Time": "0",
    "User-Agent": "curl/7.53.1",
    "Via": "1.1 vegur",
    "X-Request-Id": "4f80f5c8-09a6-4109-8ae6-2bb4f8bb71bc"
  },
  "origin": "202.37.75.230",
  "url": "http://httpbin.org/get"
}
```

**Comment by kennethreitz** [comment]
a fix has been pushed to production

**Comment by dteirney** [comment]
@kennethreitz thanks for the rapid turnaround. Have noticed now though that a sent "X-Request-Id"  parameter is always being scrubbed.

```
curl -v -H "X-Request-Id: bob" http://httpbin.org/get
*   Trying 23.23.223.197...
* TCP_NODELAY set
* Connected to httpbin.org (23.23.223.197) port 80 (#0)
> GET /get HTTP/1.1
> Host: httpbin.org
> User-Agent: curl/7.53.1
> Accept: */*
> X-Request-Id: bob
>
< HTTP/1.1 200 OK
< Server: gunicorn/19.7.1
< Date: Mon, 27 Mar 2017 20:49:37 GMT
< Content-Type: application/json
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
< Content-Length: 253
< Via: 1.1 vegur
< Connection: keep-alive
<
{
  "args": {},
  "headers": {
    "Accept": "*/*",
    "Cache-Control": "max-age=43200",
    "Connection": "close",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.53.1"
  },
  "origin": "49.224.90.214",
  "url": "http://httpbin.org/get"
}
```

Also, not sure why the `Cache-Control` header is in the response, assuming that the headers array is supposed to be the received headers.

**Comment by kmatassa** [comment]
Same observation - X-Request-Id is always being removed.

**Comment by kennethreitz** [comment]
This is an effect of being run on Heroku, and to be expected.

**Comment by kmatassa** [comment]
Bummer, this is a key header we require for testing purposes.  Httpbin is a clean tool to use, it is unfortunate that it (or its framework) is mangling headers.  Is there a work-around available?

-K

**Comment by kennethreitz** [comment]
Other than using a different header, or running httpbin yourself (e.g. with pytest-httpbin), there is no workaround. 

There are many headers that fall into this category. You can see them all here:

http://httpbin.org/get?show_env=1

**Comment by kmatassa** [comment]
Confirming, are post, patch, put, and delete are NOT supported?

**Comment by l3ender** [comment]
Just ran across this same scenario where `X-Request-Id` was not being echoed back for the `/headers` endpoint. It'd be nice if it was at least documented in the API endpoints that are affected by the side effects of the httpbin environment.
