### ISSUE TITLE
/range/ regression

### ISSUE THREAD

**Issue by lietusme** [kennethreitz/httpbin#344]
We are using /range/ to simulate slow download, it seems to be no longer transferring chunks, but rather everything in one go at the end of duration:

http://httpbin.org/range/1024?duration=10&chunk_size=2

About 2 weeks ago it was working fine - data was being sent incrementally in chunks.

Any ideas?

**Comment by nateprewitt** [comment]
It looks like b4677d7 changed /range to force a `Content-Length` header. This seems to be preventing the `Transfer-Encoding: chunked` functionality that httpbin previously had which allowed for trickled data.

**Comment by lietusme** [comment]
Does this means its broken or WAD? API allows declaring chunk_size, that does not do anything now

**Comment by nateprewitt** [comment]
I would consider it broken. The endpoint previously streamed data and is now inhibited from providing that functionality. I left a note in #314 regarding reverting this change.

**Comment by nateprewitt** [comment]
I've opened #345 to address this. Pending it's acceptance, we should have this fixed in the next release.
