### ISSUE TITLE
need refresh the ssl domain certificate

### ISSUE THREAD

**Issue by setiproz** [kennethreitz/httpbin#349]
Hi, all.
Well, I wanna do some contribution for a iOS  HTTP library--AFNetworking, which is on Github.
The AFNetworking using test case based on the SSL certificate for *.httpbin.org.
But the key ssl certificate  has been expired.

The target file link is 
https://github.com/AFNetworking/AFNetworking/blob/master/Tests/Resources/HTTPBin.org/httpbinorg_01192017.cer

I need a new one to make the test case pass.
Sorry to disturb you, but I have spend tons of time on searching the match certificate.
So, I will really appreciate if you can send me a new one.
The expired version is in the attachment.
Thank you.
my email address is setipro@163.com.

**Comment by Lukasa** [comment]
Is there any reason the certificate currently used to secure httpbin.org is not sufficient?

**Comment by Lukasa** [comment]
You can obtain this using the `openssl s_client` command line tool. 

Try `openssl s_client -connect httpbin.org -showcerts`

**Comment by setiproz** [comment]
@Lukasa thanks a lot.
