### ISSUE TITLE
what is show_env ?

### ISSUE THREAD

**Issue by xsren** [kennethreitz/httpbin#352]
Hi, I find adding **show_env** parameter will return more detailed headers, but there's no detailed description about this in the doc.

So I want ask:
1、What is **show_env**?
2、What happens in httpin if I add **show_env**?

**Comment by sigmavirus24** [comment]
If you add `show_env`, these headers will be included: https://github.com/kennethreitz/httpbin/blob/cb6795c0c66b3d8246a5a0bd099bebdf527fad52/httpbin/helpers.py#L37..L55

**Comment by xsren** [comment]
@sigmavirus24  I see. Thanks!

**Comment by mingfang** [comment]
why is this not the default?
