### ISSUE TITLE
Allow for POSTs to /response-headers

### ISSUE THREAD

**Issue by mattwwarren** [kennethreitz/httpbin#357]
I have a test case I would like to leverage httpbin for that involves making a POST to a page and expecting a particular header in order to proceed with the request chain. Unfortunately, the current endpoint only expects GETs.

Would it be possible to allow POSTs and merge the submitted headers (ala /headers) with the POST data?

I am happy to make this change but wanted to make sure it was a supported idea. Thanks in advance.

**Comment by kennethreitz** [comment]
We can make it speak POST, sure.
