### ISSUE TITLE
Header Response on /get changes case format of provided Headers

### ISSUE THREAD

**Issue by tmack8001** [kennethreitz/httpbin#363]
I understand that headers aren't case sensitive by RFC, however if httpbin is intended to be representative of what the server received then the casing of headers shouldn't be manipulated by the server of which currently looks to be doing Capital-Snake-Casing.

Steps to Reproduce:

```
$ curl -X GET \
  http://httpbin.org/get \
  -H 'x-header-capitalcase: test-valueABC'
{
  "args": {},
  "headers": {
    "Accept": "*/*",
    "Connection": "close",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.51.0",
    "X-Header-Capitalcase": "test-valueABC"
  },
  "origin": "104.192.139.233",
  "url": "http://httpbin.org/get"
}
```

```
$ curl -X GET \
  http://httpbin.org/get \
  -H 'something-else: lowercase'
{
  "args": {},
  "headers": {
    "Accept": "*/*",
    "Connection": "close",
    "Host": "httpbin.org",
    "Something-Else": "lowercase",
    "User-Agent": "curl/7.51.0"
  },
  "origin": "104.192.139.233",
  "url": "http://httpbin.org/get"
}
```

**Comment by sigmavirus24** [comment]
HTTPbin does not actually modify the headers itself [1][]. This is likely happening due to something in Flask's codebase.

[1]: https://github.com/kennethreitz/httpbin/blob/3463b5ec56795a32ac44bb3e6af8ff720198ce10/httpbin/helpers.py#L125
