### ISSUE TITLE
Would more endpoints around cookies be welcome?

### ISSUE THREAD

**Issue by adamdavis40208** [kennethreitz/httpbin#374]
I've been spending a lot of time this week in the awful land of cookies, and noticed that httpbin didn't support more complex cookies (domains, paths, expirations, etc).

While I found a way to get around this in my code (just mocking responses with Set-Cookie: with that data I wanted), I thought it'd be nice to offer to beef up httpbin so that others can easily test these silly things. 

Thoughts?

**Comment by kennethreitz** [comment]
I think I like the simplicity of what we offer now.
