### ISSUE TITLE
/delay for (a bit) longer waits to short?

### ISSUE THREAD

**Issue by JacobOscarson** [kennethreitz/httpbin#375]
Just measured the `/delay` endpoint (Fri Aug 11 12:32:31 UTC 2017) with a `:n` parameter of `61`, double checking with a stopwatch on my phone to ensure I'm not reading something wrong, I saw this:

```shell
$ time curl https://httpbin.org/delay/61
{
  "args": {},
  "data": "",
  "files": {},
  "form": {},
  "headers": {
    "Accept": "*/*",
    "Connection": "close",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.54.0"
  },
  "origin": "213.115.5.18",
  "url": "https://httpbin.org/delay/61"
}

real	0m10.616s
user	0m0.023s
sys	0m0.017s
```

Shouldn't the time consumed be more like over a minute?

**Comment by kennethreitz** [comment]
There's a max set to 10 seconds.

**Comment by kennethreitz** [comment]
https://github.com/kennethreitz/httpbin/blob/master/httpbin/core.py#L525

**Comment by kennethreitz** [comment]
That endpoint is a great way to DDOS this service, so it's set to something reasonable. 10s is a LONG TIME to keep a connection open on the interwebs.

**Comment by dkeightley** [comment]
If it helps, I created a replica of httpbin that can handle long delays - https://hub.docker.com/r/derekdemo/httpbin
