### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by chassing** [kennethreitz/httpbin#378]
hi,

please release a new version with all new features (e.g. /anything) on pypi. 0.5.0 has been release a year ago.

thx

**Comment by kennethreitz** [comment]
Someone maintains the pypi releases... can't remember who

**Comment by chassing** [comment]
I think it should be enough to increase the version number in setup.py and travis will take care of the rest. have a look into your .travis.yml, @sigmavirus24 added all the magic with commit dc7e81c4a1a372f2cae25d126066c275e5ebaf06

**Comment by kennethreitz** [comment]
woah if that's true, send a PR and i'll merge it!

**Comment by kennethreitz** [comment]
@sigmavirus24 if this is true you get a cookie or three 🍪 🍪 🍪

**Comment by chassing** [comment]
here we go #379

**Comment by chassing** [comment]
looks like the current .travis.yml is a different one to dc7e81c 😢  but I can't figure why. I would say lets wait for @sigmavirus24

**Comment by sigmavirus24** [comment]
You're looking at the `tox.ini` which has little correlation to `.travis.yml`. I didn't set up Travis to automate releases, but all one has to do is `tox -e release` with the latest version of master.

**Comment by kennethreitz** [comment]
fine, i'll do it

**Comment by chassing** [comment]
You are right ... I should go to 🛏 now 😢

**Comment by kennethreitz** [comment]
doesn't work on my machine — i'll try the oldschool way

**Comment by kennethreitz** [comment]
i don't have creds on this machine — and my other machine just died. may be delayed.

**Comment by sigmavirus24** [comment]
I'll release the new version, @kennethreitz

**Comment by kennethreitz** [comment]
thanks man :)

**Comment by sigmavirus24** [comment]
And done. 🍰

**Comment by kennethreitz** [comment]
✨🍰✨
