### ISSUE TITLE
flask_common imported, but not used for anything

### ISSUE THREAD

**Issue by AdamWill** [kennethreitz/httpbin#381]
Unless I'm missing something, this commit seems a bit bizarre: https://github.com/kennethreitz/httpbin/commit/a39de83be1b7330f6a99981bf54152c525847299 . Neither it nor any subsequent commit seems to *do* anything with common - it just pulls it in, does the initial setup, and...nothing else. Is it just a vestige of some plan that didn't go ahead?

**Comment by kennethreitz** [comment]
It's adding response headers, like how much time the http response took to process.

**Comment by kennethreitz** [comment]
```$ curl -I http://httpbin.org/ip

HTTP/1.1 200 OK
Connection: keep-alive
Server: meinheld/0.6.1
Date: Wed, 30 Aug 2017 17:34:07 GMT
Content-Type: application/json
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
X-Powered-By: Flask
X-Processed-Time: 0.000820159912109
Content-Length: 31
Via: 1.1 vegur
```

**Comment by AdamWill** [comment]
aha, I see. it might be nice to have a comment or something explaining that, since it's not at all obvious from the code or the commit message. thanks!
