### ISSUE TITLE
Move compression-related endpoints

### ISSUE THREAD

**Issue by vanillajonathan** [kennethreitz/httpbin#390]
Move the `/gzip`, `/deflate` and `/brotli` endpoints to under a `/compression` or `/compressed` hierarchy.
i.e. `/compression/gzip` so they are grouped together like is done for the `/encoding/utf8` and `/image/png` endpoints.

**Comment by sigmavirus24** [comment]
Thanks for the suggestion. I'm not sure we want to do that. This is a result of organic growth and several people are already relying on those endpoints. I'd rather not duplicate and using redirects may break those users unexpectedly.

**Comment by vanillajonathan** [comment]
Well you could create those endpoints and then both endpoints go to the same resource.
Then analyze the incoming traffic and see if anyone still relies on the old endpoints, then eventually remove them.
