### ISSUE TITLE
I see SSL issue with this URL --> https://httpbin.org/basic-auth/user/passwd

### ISSUE THREAD

**Issue by Vishnu10987** [kennethreitz/httpbin#407]
I see this URL is failing since the last few days and my logs indicate an SSL issue .  Could you plesae let me know if any SSL setup has been changed recently .

Below are the logs I can see which indicate an SSL issue between my server and httpbin

Outbound HTTP on new TCP session using HTTP/1.1 to https://httpbin.org/basic-auth/user/passwd
20171204T162253.179Z [0x80e00626][network][error] : tid(246197795)[] gtid(246197795): Error occurred when connecting to URL 'https://httpbin.org/basic-auth/user/passwd'
20171204T162253.179Z [0x8120002f][ssl][error] ssl-client(api-sslcli-all): tid(246197795)[] gtid(246197795): SSL library error: error:140780E5:SSL routines:ssl23_read:ssl handshake failure
20171204T162253.179Z [0x80e00040][network][error] mpgw(webapi): tid(246197795)[request][133.29.0.2] gtid(246197795): url-open: Remote error on url 'https://httpbin.org/basic-auth/user/passwd'

**Comment by sigmavirus24** [comment]
I cannot reproduce this on my machine using cURL or other HTTP clients. This seems to be an issue on your end. Perhaps your SSL configuration changed and is now broken.
