### ISSUE TITLE
404 for trailing slash

### ISSUE THREAD

**Issue by loganvolkers** [kennethreitz/httpbin#408]
Can we get support for trailing slashes?

 - https://httpbin.org/status/200  -- Returns a 200
 - https://httpbin.org/status/200/ -- Returns a 404 (ideally should just a 200)

Seems like it should be a straightforward change, and something we need at our org for running a custom instance of httpbin.

**Comment by sigmavirus24** [comment]
> our org for running a custom instance of httpbin.

If you're not relying on httpbin.org, why not simply modify the server (nginx, apache) to handle `/status/200/` and `/status/200` the same? There are rules for this in those configs.

**Comment by loganvolkers** [comment]
Thanks for the suggestion, that's what I ended up doing.
