### ISSUE TITLE
Feature request | hanging connections / timeouts tests

### ISSUE THREAD

**Issue by AlmogBaku** [kennethreitz/httpbin#409]
Option to add a delay between the time of the request to the response in order to test how the client handles hanging requests (i.e. timeout of waiting for response, timeout for connect, etc)

**Comment by sigmavirus24** [comment]
See also #26 #227 #338 and #375 

There's already a `/delay` endpoint. It has a max delay of 10 seconds (which should be enough for 98% of httpbin's target user base). We can't control a connection delay, but we can control a delay in returning a response.

We can't increase the maximum delay. And the above linked issues (easily findable through GitHub's issue search) explain other constraints we have pretty well.

Cheers!
