### ISSUE TITLE
HTTP 500 errors for digest auth

### ISSUE THREAD

**Issue by jeroen** [kennethreitz/httpbin#415]
As of earlier today my http client unit tests started failing because the `digest-auth` endpoint returns HTTP 500 instead of 200 for correct credentials. Example:

```
curl https://eu.httpbin.org/digest-auth/auth/jerry/secret -v -u jerry:secret
```

Has there been a new deployment? It was working OK for the past months, maybe even years.

**Comment by sigmavirus24** [comment]
This could be related to https://github.com/kennethreitz/httpbin/commit/9e9cb84724cfb72e7780a7c37c59468e55bb8f0d but it's unclear to me if @kennethreitz has deployed recently

**Comment by sigmavirus24** [comment]
Looking a little closer I see:

```
*  SSL certificate verify ok.
* Server auth using Basic with user 'jerry'
> GET /digest-auth/auth/jerry/secret HTTP/1.1
> Host: eu.httpbin.org
> Authorization: Basic amVycnk6c2VjcmV0
> User-Agent: curl/7.54.0
> Accept: */*
```

From the `curl` output. It seems like httpbin was incorrectly accepting basic auth credentials for digest auth. We should investigate more to understand what the behaviour was previously.

**Comment by jeroen** [comment]
Yes that is correct. The problem is it now returns a `HTTP 500` (which indicates a server bug).

What should be happening, and was happening before, is that the server ignores the basic auth and returns `HTTP 421 UNAUTHORIZED` along with the proper `www-authenticate` header according to the http digest protocol. This invites the client to make a subsequent request including the proper `Authorization` header.

This does work:

```
curl https://eu.httpbin.org/digest-auth/auth/jerry/secret -v -u jerry:secret --digest
``

But really this should also work (and it used to):

```
curl https://eu.httpbin.org/digest-auth/auth/jerry/secret -v -u jerry:secret
```

The client doesn't have to know in advance that the server wants to use digest auth. If it first tries to authenticate basic auth the server should ignore the basic auth credentials and continue with the digest auth dance, not just error.

**Comment by sigmavirus24** [comment]
Right, I'm not arguing that it should 500. I agree that's wrong. I'm trying to discern what the default behaviour *was*

**Comment by jeroen** [comment]
OK cool. AFAIK the previous (and correct) behaviour for the digest auth API is simply to ignore the basic auth header and respond identically as when no basic auth header was sent.

**Comment by jeroen** [comment]
I reproduced this with the official httpbin docker image. Below a stack trace:

```
[2017-12-20 22:42:25,748] ERROR in app: Exception on /digest-auth/auth/jerry/secret [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/httpbin/core.py", line 497, in digest_auth_md5
    return digest_auth(qop, user, passwd, "MD5", 'never')
  File "/usr/local/lib/python3.6/site-packages/httpbin/core.py", line 554, in digest_auth
    response.set_cookie('last_nonce', value=current_nonce)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/wrappers.py", line 1101, in set_cookie
    max_size=self.max_cookie_size
  File "/usr/local/lib/python3.6/site-packages/werkzeug/http.py", line 1058, in dump_cookie
    buf = [key + b'=' + _cookie_quote(value)]
  File "/usr/local/lib/python3.6/site-packages/werkzeug/_internal.py", line 228, in _cookie_quote
    for char in iter_bytes(b):
TypeError: 'NoneType' object is not iterable
```

**Comment by nateprewitt** [comment]
This appears to be another bug introduced by #366. It’s odd it didn’t crop up until recently, did we not deploy changes to eu.httpbin.org when we last deployed to the base domain?

Either way our [check in digest_auth](https://github.com/kennethreitz/httpbin/blob/master/httpbin/core.py#L521) is seeing the existing Authorization header and bypassing the 401 response. I believe we need to fix the conditional to verify the header is explicitly digest-auth authorization.

**Comment by jeroen** [comment]
Interestingly a very similar bug was fixed 3 years ago: https://github.com/kennethreitz/httpbin/issues/162

**Comment by jeroen** [comment]
I checked with old releases and the problem was introduced [between tags v0.6.1 and v0.6.2](https://github.com/kennethreitz/httpbin/compare/v0.6.1...v0.6.2). The problem is not present in the v0.6.1 docker container.

**Comment by nateprewitt** [comment]
Yeah, it looks like #392 is where this was actually exposed to the end user because of the modified cookie check. The above approach is likely still the fix we want.

**Comment by jeroen** [comment]
Ping. Still stuck on this :( @nateprewitt could you maybe suggest a fix? I am not familiar enough with python to further debug this than narrowing it down to the 0.6.2 release.

**Comment by nateprewitt** [comment]
@jeroen I believe the bug was identified and the solution suggested in the [above comment](https://github.com/kennethreitz/httpbin/issues/415#issuecomment-353208804). We just need to get the work done and a new version of httpbin shipped.

**Comment by jeroen** [comment]
OK well lmk if there is anything I can help to move this forward, because it's breaking my auth unit tests :)

**Comment by nateprewitt** [comment]
If you’d be interested in creating a pull request that’s definitely welcomed. Otherwise, I’ll try to get to this sometime this weekend.

**Comment by QuLogic** [comment]
The R-curl [unit test](https://github.com/jeroen/curl/blob/master/tests/testthat/test-auth.R#L16) seems to think this should still return 200, but it seems to return 401. Does that need updating?
