### ISSUE TITLE
Hosted httpbin doesn't drip

### ISSUE THREAD

**Issue by yschimke** [kennethreitz/httpbin#417]
same as https://github.com/kennethreitz/httpbin/issues/252

Tested with curl and OkHttp

curl -v 'https://httpbin.org/drip?numbytes=5000&code=200&duration=10&delay=2'

**Comment by sigmavirus24** [comment]
Heroku has a proxy that lives between you and httpbin. Can you test locally to see if it's dripping or not? That will help narrow down whether this is a PaaS problem or actually a bug in httpbin

**Comment by yschimke** [comment]
Works locally - although the curl command I gave doesn't show it.

with OkHttp Progress Example https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/Progress.java

```
1
500
false
0% done
23
500
false
4% done
24
500
false
4% done
25
500
false
5% done
26
500
false
5% done
27
500
false
5% done
28
500
false
5% done
```

**Comment by sigmavirus24** [comment]
Right, since this relates to the version hosted by Heroku, there's literally nothing this project can do. As such, there's no bug to fix and this issue is invalid.

**Comment by yschimke** [comment]
Useful alternative host supporting HTTP/2 https://nghttp2.org/httpbin/

**Comment by cup** [comment]
https://github.com/postmanlabs/httpbin/issues/252
https://github.com/postmanlabs/httpbin/issues/348
https://github.com/postmanlabs/httpbin/issues/417
https://github.com/postmanlabs/httpbin/issues/541
