### ISSUE TITLE
Enable request logging

### ISSUE THREAD

**Issue by drichards-levtech** [kennethreitz/httpbin#421]
This is more a feature enhancement 
I would like to be able to see (on the server/docker side) the requests that are being sent in.

This would allow me to inspect the data that clients are sending to /get or /anything or maybe it is a new endpoint /logme without having to resort to wireshark.

Thanks in advance

**Comment by sigmavirus24** [comment]
Hi there,

Depending on how you set-up httpbin, you could absolutely log this without adding to HTTPbin. For example, with nginx, you can specify `$request_body` in your `log_format` to see the actual data.

Given the options, I'd be inclined to reject this feature enhancement.

**Comment by drichards-levtech** [comment]
I was thinking more from the Docker side of things, currently I just run the container and would just prefer to not have to build my own image with updated nginx settings. Having an option like the debug would allow me to always pull the "official" image. 

`docker run -e "DEBUG=True" --rm --name "httpbin" kennethreitz/httpbin
`

**Comment by sigmavirus24** [comment]
So, fundamentally, you will not see the data that clients are sending to those endpoints any differently than you already do.

```
$ curl https://httpbin.org/anything --data-binary foo=bar
{
  "args": {},
  "data": "",
  "files": {},
  "form": {
    "foo": "bar"
  },
  "headers": {
    "Accept": "*/*",
    "Connection": "close",
    "Content-Length": "7",
    "Content-Type": "application/x-www-form-urlencoded",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.54.0"
  },
  "json": null,
  "method": "POST",
  "origin": "204.14.239.105",
  "url": "https://httpbin.org/anything"
}
```

`/anything` already returns the data *as it is seen by HTTPbin*. So your mention of wireshark makes it seem like you want something that isn't processed yet. By the time it would get to a `/logme` endpoint it would already have been processed and there's not much value to that.

Then again, all you've told me is that you want to avoid wireshark, not why you're presently using it so I really can't help you.

**Comment by drichards-levtech** [comment]
Why we would like it, is that we use a local httpbin docker as backend to the APIs we create to allow us to test without official backends as well as examine how the API Management solution works. For example to examine what headers are sent during an OAuth exchange or how data is sent over for an Authentication URL.  The issue is that the software doesn't show us what was returned from the authentication call only if it was a 200 or not, thus we have no visibility into what was passed in nor out without sniffing the wire. Having the ability to have our httpbin log the request/response just as it would be sending back allows us to debug the calls by watching the docker logs.

What I did locally is to add a `app.logger.debug(get_dict(..))` call in the `/anything` route to test and will put it into each route as we need to set some custom headers for the software to work.

**Comment by Lucas-C** [comment]
@ drichards-levtech this is the Dockerfile I use to configure `gunicorn` to send access & error logs to stdout:
```
FROM python:3.6
RUN pip install gunicorn httpbin
ENV GUNICORN_CMD_ARGS="--bind=0.0.0.0:8000 --workers=3 --capture-output --error-logfile - --access-logfile - --access-logformat '%(h)s %(t)s %(r)s %(s)s Content-Type: %({Content-Type}i)s'"
CMD ["gunicorn", "httpbin:app"]
```

Sadly, no way to log the request body as it is a buffer in `gunicorn`.

This would have to be implemented in `httpbin`, or as @sigmavirus24 suggested, through an intermediate server layer like `nginx` that provides this information.

**Comment by Lucas-C** [comment]
In this end I used this recipe:
https://github.com/voyages-sncf-technologies/nginx-logging-proxy-demo

**Comment by drichards-levtech** [comment]
Thanks for the update I will checkout the proxy image from lucascimon/nginx-logging-proxy

**Comment by jsw** [comment]
I landed here looking for the same thing. I want to deploy a docker image that will simply log info about the request, specifically the `Host` header. For reference, this works for that use case

```
docker run -p 8080:8080 -e GUNICORN_CMD_ARGS="--capture-output --error-logfile - --access-logfile - --access-logformat '%(h)s %(t)s %(r)s %(s)s Host: %({Host}i)s}'" kennethreitz/httpbin
```

**Comment by alainchiasson** [comment]
To get the above working in docker compose ( the % mess it up ), use an external .env file and do the substitution ( see See : https://docs.docker.com/compose/env-file/).

In the same directory : 

.env
```
GUNICORN_CMD_ARGS=--capture-output --error-logfile - --access-logfile - --access-logformat '%(h)s %(t)s %(r)s %(s)s Host: %({Host}i)s}'
```

docker-compose.yml
```
version: '3'
services:
  httpbin:
    image: kennethreitz/httpbin
    ports:
     - "80:80"
    environment:
      - GUNICORN_CMD_ARGS=${GUNICORN_CMD_ARGS}

```
