### ISSUE TITLE
Question: has been there a limit for https://httpbin.org/post ?

### ISSUE THREAD

**Issue by FrancescoMussi** [kennethreitz/httpbin#422]
Hello,
I write to ask for a clarification.

For the previous two weeks I was unable to upload files to https://httpbin.org/post bigger than 200kb.
Today I noticed that this is no longer an issue.
There has been in place some kind of size limit for the past 2/3 weeks?

To be more specific:
I have been using a dropzone component for vue: [vue-dropzone](https://github.com/rowanwins/vue-dropzone)
that make use of https://httpbin.org/post as an endpoint.
And for that period I was unable to post images > 200kb.
This is issue referecing this problem: https://github.com/rowanwins/vue-dropzone/issues/279

Since I am about to go in production, can I be sure that there won't be anymore this kind of limit?

Thanks!

**Comment by sigmavirus24** [comment]
Hi @FrancescoMussi 

There was no limit inside of HTTPbin. If any limiting was happening it was happening due to our platform provider. I don't think anything of consequence has been merged or deployed of late.

I don't know why httpbin would affect your production deployment, however.

**Comment by FrancescoMussi** [comment]
Okay thanks for the answer.
