### ISSUE TITLE
Expect: 100-continue timeout

### ISSUE THREAD

**Issue by samoconnor** [kennethreitz/httpbin#429]
If I send a post request with a `Expect: 100-continue` header, httpbin.org responds with a timeout:
```julia
julia> HTTP.request("POST", "http://httpbin.org/post", ["Expect" => "100-continue"], "FOOBAR"; verbose=3)
➡️   "POST /post HTTP/1.1\r\n"
➡️   "Expect: 100-continue\r\n"
➡️   "Host: httpbin.org\r\n"
➡️   "Content-Length: 6\r\n"
➡️   "\r\n"
⬅️   "HTTP/1.1 408 Request Timeout\r\n"
    "Date: Fri, 02 Mar 2018 05:06:11 GMT\r\n"
    "Connection: close\r\n"
    "Content-Type: text/html\r\n"
    "Server: meinheld/0.6.1\r\n"
    "Via: 1.1 vegur\r\n"
    "\r\n"
```

If I modify the client so that it does not wait for the `HTTP/1.1 100 Continue` response, but just sends the body right away, then httpbin.org responds with `HTTP/1.1 100 Continue` immediatly followed by `HTTP/1.1 200 OK`...
```julia
julia> HTTP.request("POST", "http://httpbin.org/post", ["Expect" => "100-continue"], "FOOBAR"; verbose=3)
➡️   "POST /post HTTP/1.1\r\n"
➡️   "Expect: 100-continue\r\n"
➡️   "Host: httpbin.org\r\n"
➡️   "Content-Length: 6\r\n"
➡️   "\r\n"
➡️   "FOOBAR"
⬅️   "HTTP/1.1 100 Continue\r\n"
    "\r\n"
    "HTTP/1.1 200 OK\r\n"
```

It would appear that httpbin.org is waiting for the 6-byte payload body then retuning 408 Request Timeout. It should not do this when a `Expect: 100-continue` header is present.

**Comment by sigmavirus24** [comment]
You're relying on a service hosted on another service which does not support 100-continue. I strongly advise using something else to test this use-case.

**Comment by samoconnor** [comment]
> I strongly advise using something else to test this use-case.

I am. I just thought that since you are running a test service, you might appreciate feedback about corner cases where it doesn't work. Perhaps this issue should be left open so that the next person who runs into the problem can see that it has been considered. I completely understand if it is not a priority to fix this, but as it stands it is clearly not standards compliant.

**Comment by sigmavirus24** [comment]
> Perhaps this issue should be left open so that the next person who runs into the problem can see that it has been considered.

No. This project will not leave bugs open indefinitely. Any user of GitHub or Google can find this as it is. It's closed which mean it has been considered.

> as it stands it is clearly not standards compliant.

And it's out of this tiny project's control.
