### ISSUE TITLE
OPTIONS / works, but OPTIONS * returns 404 not found

### ISSUE THREAD

**Issue by samoconnor** [kennethreitz/httpbin#430]
`OPTIONS / HTTP/1.1` works, but [`OPTIONS * HTTP/1.1`](https://tools.ietf.org/html/rfc7231#section-4.3.7) returns 404 not found:

```julia
julia> HTTP.request("OPTIONS", "https://httpbin.org";verbose=3)
➡️   "OPTIONS / HTTP/1.1\r\n"
➡️   "Host: httpbin.org\r\n"
➡️   "Content-Length: 0\r\n"
➡️   "\r\n"
⬅️   "HTTP/1.1 200 OK\r\n"
    "Connection: keep-alive\r\n"
    "Server: meinheld/0.6.1\r\n"
    "Date: Fri, 02 Mar 2018 06:16:52 GMT\r\n"
    "Content-Type: text/html; charset=utf-8\r\n"
    "Allow: HEAD, OPTIONS, GET\r\n"
    "Access-Control-Allow-Origin: *\r\n"
    "Access-Control-Allow-Credentials: true\r\n"
    "Access-Control-Allow-Methods: GET, POST, PUT, DELETE, PATCH, OPTIONS\r\n"
    "Access-Control-Max-Age: 3600\r\n"
    "X-Powered-By: Flask\r\n"
    "X-Processed-Time: 0\r\n"
    "Content-Length: 0\r\n"
    "Via: 1.1 vegur\r\n"
    "\r\n"
HTTP.Messages.Response:
"""
HTTP/1.1 200 OK
Connection: keep-alive
Server: meinheld/0.6.1
Date: Fri, 02 Mar 2018 06:16:52 GMT
Content-Type: text/html; charset=utf-8
Allow: HEAD, OPTIONS, GET
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, PATCH, OPTIONS
Access-Control-Max-Age: 3600
X-Powered-By: Flask
X-Processed-Time: 0
Content-Length: 0
Via: 1.1 vegur

"""

julia> HTTP.request("OPTIONS", "http://httpbin.org"; target = "*", verbose=3)
➡️   "OPTIONS * HTTP/1.1\r\n"
➡️   "Host: httpbin.org\r\n"
➡️   "Content-Length: 0\r\n"
➡️   "\r\n"
⬅️   "HTTP/1.1 404 NOT FOUND\r\n"
    "Connection: keep-alive\r\n"
    "Server: meinheld/0.6.1\r\n"
    "Date: Fri, 02 Mar 2018 06:16:58 GMT\r\n"
    "Content-Type: text/html\r\n"
    "Content-Length: 233\r\n"
    "Access-Control-Allow-Origin: *\r\n"
    "Access-Control-Allow-Credentials: true\r\n"
    "Access-Control-Allow-Methods: GET, POST, PUT, DELETE, PATCH, OPTIONS\r\n"
    "Access-Control-Max-Age: 3600\r\n"
    "X-Powered-By: Flask\r\n"
    "X-Processed-Time: 0\r\n"
    "Via: 1.1 vegur\r\n"
    "\r\n"
    "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\n"
    "<title>404 Not Found</title>\n"
```

**Comment by sigmavirus24** [comment]
`OPTIONS *` is part of the specification but not well supported. It's also not supported by the router that the hosting service httpbin.org uses and it's also not supported in general by Python HTTP services.

**Comment by samoconnor** [comment]
So, shouldn't this ticket be left open as a failing test case?
Surely it should be the goal of everyone working on HTTP infrastructure to be as standards compliant as possible and to be transparent about thing that are not implemented. e.g. file an upstream bug with the hosting service?

**Comment by sigmavirus24** [comment]
> So, shouldn't this ticket be left open as a failing test case?

Anyone can find this issue. Leaving it open indefinitely is rather pointless.

> Surely it should be the goal of everyone working on HTTP infrastructure to be as standards compliant as possible

Certainly it should be, but it isn't. Further, this is a service for testing the 90% use-case, or roughly that amount. If the stacks we rely on don't support something, it's not on us to rigorously track down every last bug and fix it. The couple of us that actually attempt to maintain this have far more rich and varied lives that don't afford us the infinite time your comment implies we have to work on a bug that's come up for the first time in several years.
