### ISSUE TITLE
Content-Length: 0 incorrectly send for /status/204

### ISSUE THREAD

**Issue by micgro42** [kennethreitz/httpbin#437]
http://httpbin.org/status/204 incorrectly sends a `Content-Length: 0` header. This is not allowed per RFC7320:

> A server MUST NOT send a Content-Length header field in any response
   with a status code of 1xx (Informational) or 204 (No Content).

https://tools.ietf.org/html/rfc7230#section-3.3.2

**Comment by sigmavirus24** [comment]
If I run the app locally, I don't see that:

```
~/s/httpbin ❯❯❯ curl -vv http://127.0.0.1:8001/status/204               < master
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8001 (#0)
> GET /status/204 HTTP/1.1
> Host: 127.0.0.1:8001
> User-Agent: curl/7.55.1
> Accept: */*
> 
< HTTP/1.1 204 NO CONTENT
< Server: meinheld/0.6.1
< Date: Sat, 14 Apr 2018 13:04:16 GMT
< Content-Type: text/html; charset=utf-8
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
< X-Powered-By: Flask
< X-Processed-Time: 0
< Connection: Keep-Alive
< 
* Connection #0 to host 127.0.0.1 left intact
```

If you're seeing that on `httpbin.org` that's because there's a proxy that Heroku runs between the service and you that is adding that.
